name: smb_backup
description: Dart script that compresses a folder and stores it on a smb share (including WoL if server is not available)
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  dart_ping: ^9.0.1
  wake_on_lan: ^4.1.1+3
  archive: ^4.0.2
  path: ^1.9.1
  smb_connect: ^0.0.5
  args: ^2.6.0
  mailer: ^6.4.0

dev_dependencies:
  lints: ^5.0.0
